### PR TITLE
Support epc3 and introduce 'one fits all' epc update

### PR DESCRIPTION
**Pull request by hhoegelo**

### CODE REVIEW

**Comment by hhoegelo** [comment]
> will this PR close #3089?

Yes

**Comment by schlenkibus** [comment]
- [ ] review playground for usage of EPC platform string

**Comment by AntonSchmied** [comment]
this should also close #2985

**Comment by AntonSchmied** [comment]
The README (https://github.com/nonlinear-labs-dev/C15/blob/epc3/README.md) should be updated before merging.

**Comment by AntonSchmied** [comment]
Unfortunately the playground does not start. locale seems to cause the problem
```
 [root@archlinux sscl]# /usr/local/C15/playground/playground --bbbb-host=192.168.10.11 --midi-bridge=192.168.10.11 --layouts=/usr/local/C15/playground/resources/templates
terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not set locale to en_US.utf8@nonlinear.UTF-8 or at least en_US.utf8 
Aborted (core dumped)
[root@archlinux sscl]# locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US@nonlinear.UTF-8
LC_CTYPE="en_US@nonlinear.UTF-8"
LC_NUMERIC="en_US@nonlinear.UTF-8"
LC_TIME="en_US@nonlinear.UTF-8"
LC_COLLATE="en_US@nonlinear.UTF-8"
LC_MONETARY="en_US@nonlinear.UTF-8"
LC_MESSAGES="en_US@nonlinear.UTF-8"
LC_PAPER="en_US@nonlinear.UTF-8"
LC_NAME="en_US@nonlinear.UTF-8"
LC_ADDRESS="en_US@nonlinear.UTF-8"
LC_TELEPHONE="en_US@nonlinear.UTF-8"
LC_MEASUREMENT="en_US@nonlinear.UTF-8"
LC_IDENTIFICATION="en_US@nonlinear.UTF-8"
LC_ALL=
```

**Pull request merged**
