### PR TITLE
issue 2589

### LINKED ISSUE #2589: MIDI Mappings: zusätzlicher Eintrag "High-Res. CCs (use LSBs)" (On/Off)
Das ist jetzt erst einmal eine globale Lösung für die Anforderung, auch reine 7-Bit CCs anzubieten. Wir schalten also einfach für alle verwendeten Control Changes die LSBs an oder aus, d.h. wir verschicken sie oder nicht und wir reagieren auf sie oder nicht.
In der Semantik ist es konsistent zu "High-Res. Velocity"

- [ ] add "none" to all mappings

### PR DESCRIPTION
**Pull request by schlenkibus**
added 14 bit option, this enabled/disabled 14 bit sending and receiving of LSB CC values
closes #2589

### CODE REVIEW

**Review by MatthiasSeeber — APPROVED** [review]
First IDE Tests show expected behavior for Receive. Seemingly, None and 7-Bit options work. Setup MIDI Settings did not change, but kept their values. Regarding Receive Details and Send in general, we need to perform some further tests on the C15.

**Comment by schlenkibus** [comment]
> First IDE Tests show expected behavior for Receive. Seemingly, None and 7-Bit options work. Setup MIDI Settings did not change, but kept their values. Regarding Receive Details and Send in general, we need to perform some further tests on the C15.

use this installer to test on the device
https://we.tl/t-lCPs8742gD

**Comment by schlenkibus** [comment]
new test build: https://we.tl/t-74kUO454w9

**Review by MatthiasSeeber — APPROVED** [review]

**Review by hhoegelo — APPROVED** [review]
To consider: decide for either magic numbers or std::optional<>

**Comment by schlenkibus** [comment]
refactoring was outsourced to isse-2589-refactor as more tests failed then usual

**Pull request merged**
