### PR TITLE
fix "playcontroller targets do always build"

### PR DESCRIPTION
**Pull request by hhoegelo**

### CODE REVIEW

**Comment by KlausStrohhaecker** [comment]
co-proc must rebuild when
- its binary is missing (not yet built)
- its local source files change
- the local shared files change (\projects\playcontroller\firmware\src\shared)
- the global shared files change (\projects\shared\version.h)

main must rebuild when
- its binary is missing (not yet built)
- its local source files change
- the local shared files change (\projects\playcontroller\firmware\src\shared)
- the global shared files change (\projects\shared\version.h and projects\shared\playcontroller\playcontroller-*)
- co-proc was rebuilt

do the changes afford that?

Personally, I would't mind force-building both parts unconditionally in the proper order (co-proc first, then main) as the project is small and compiles quickly. Of course only if playcontroller is actually an (update-)target.

**Comment by hhoegelo** [comment]
Ich kriege leider solche Fehler, wenn ich das Projekt ohne den Fix bauen moechte:

CMake Error at build-tools/playcontroller/cmake_install.cmake:42 (include):
  include could not find load file:

    /workdir/projects/cmake_install.cmake
Call Stack (most recent call first):
  build-tools/cmake_install.cmake:45 (include)
  cmake_install.cmake:43 (include)


make: *** [Makefile:129: install] Error 1
07:46:49: The process "/usr/bin/cmake" exited with code 2.
Error while building/deploying project C15 (kit: CCache)
When executing step "CMake Build"

**Comment by hhoegelo** [comment]
Ich wuerde sagen, Deine geschilderten Requirements sind doch genau das, was man mit den CMakeLists.txt ausdrueckt, oder? Vielleicht verstehe ich auch etwas falsch?

**Comment by KlausStrohhaecker** [comment]
Looks like the whole thing was a glitch observed by someone not fully aware of the dependencies. When I'm building, using today's "unstable", `make playcontroller-blobs` behaves exactly as expected:

- touch a file in "main" sources :  compile & link main
- touch a file "co-proc" sources : compile & link co-proc, then re-link main
- touch a file in local "shared" sources : complile & link co-proc, then compile & link main
- touch a file in global "shared" sources like "playcontroller_defs.h" or the global C15 "version.h" (which contains __DATE__ and __TIME__ macros) : complile & link co-proc, then compile & link main

Thereafter, `make playcontroller-blobs` does nothing, as expected. Same applies for a full c15-update build.

**Comment by KlausStrohhaecker** [comment]
Futher, test-merging this PR into "unstable" and repeating above steps (after a refreshed cmake) does *nothing* in all cases, so something seems broken here anyway (I did not double-check with emptied build dir `builds/C15/build-tools/playcontroller`,  though)

@hhoegelo , I suggest closing this with no further action and remove the branch

**Pull request closed without merging**
