### PR TITLE
Issue 3158, 3251

### LINKED ISSUE #3158: Loop Funktion für Envelope C
Es wird ein neues Feature eingeführt, welches Envelope C für die Phase zwischen Breakpoint und Sustain loop-bar macht. Das bedeutet, dass ein neuer Parameter mit Namen "**Loop**" eingeführt wird. Der Parameter hat einen Wertebereich von 0%-200% und wird in der UI im Stack unter Sustain platziert. Steht der Parameter auf 0% ist Loop ausgeschaltet und der Envelope verhält sich wie gewohnt. Steht der Parameter auf 100%, wird der Envelope zwischen Breakpoint und Sustain geloopt, d.h. 
- Envelope startet mit der Attackphase und läuft bis zum Erreichen des Sustainlevels ganz normal durch
- sobald das Sustainlevel erreicht ist, geht der Envelope in Decay 1 Zeit zum Breakpoint und von dort in Decay 2 Zeit zum Sustain Level usw. 

Hierfür muss Decay 2 linear werden. Das passiert, sobald Loop > 0.

Loop ist ein Faktor, deshalb auch der Wertebereich von 0% - 200% (bzw. 0-2). 
Es wird zunächst der Betrag aus der Differenz von Breakpoint und Sustain gebildet. Mit dem ersten Loop, d.h. nach dem ersten regulären Durchlauf des Envelopes zum Sustainlevel, wird dieser Betrag mit dem Loopfaktor multipliziert und im nächsten Loop der erhaltene neue Betrag erneut mit dem Loopfaktor multipliziert usw. Dadurch nähert sich für Loop < 1 der Breakpoint dem Sustain mit jedem Loopdurchlauf an und man erhält einen abkligenden Loop, der in das Sustainlevel übergeht. Für Loop = 1 klingt der Loop dementsprechend nicht ab. 

Für Loop <= 1 wird mit dem NoteOff wie gewohnt die Release Phase des Envelopes getriggert. Bei Loop > 1 bleibt der Envelope auch mit dem NoteOff im Loop. Solange NoteOn, verhält sich der Envelope für Loop > 1 wie für Loop = 1, d.h. Faktor = 1. Sobald NoteOff, ergibt sich der Faktor aus Faktor = Loop - 1. Das bedeutet, dass für Loop < 2, der Loop mit NoteOff langsam abklingt, für Loop = 2 nie abklingt. 

Zusätzlich wird der schon von Attack und Release bekannte Velocity-Parameter auch für Decay 1 und Decay 2 eingeführt. 

Der Loop-Parameter ist modulierbar. 

**Vorschlag für einen Infotext:**
At a setting of 100%, the envelope is looped between the breakpoint and the sustain level. If the value is between 0 and 100%, the loop decays by this factor to the sustain level. If the value is above 100%, the release phase is not triggered when a key is released, but the loop decays to the sustain level by the value minus 100%. If the value is 200%, the loop will never decay. 
When the loop is activated, Decay 2 decays linearly, not exponentially. 

**Zusammenfassung:**
Envelope C wird zwischen BP und Sustain loopfähig. Der Loop kann wahlweise unendlich, zum Sustainlevel abklingend oder mit NoteOff in die Releasephase übergehend sein. Es gibt die drei neuen Parameter Loop (0-200%), Decay 1 und 2 Velocity (-60 bis 60 dB). 

P.S.: Es gibt eine funktionierende Core-Implementierung.

### LINKED ISSUE #3251: Envelope Enhancements
- [x] Bug: Envelope B Decay 1/2 Velocity has influence on Envelope C Decay 1/2 Times

see [milestone-synthengine-update] `.../c15-audio-engine/ae_poly_section.cpp[918/919]`

The variables `decay1vel, decay2vel` are wrongfully used in the Env C section without them being set to zero. Before, they are set by Env B. This looks like a copy/paste mishap and will become irrelevant when implementing #3158 (which aims for Env C Dec 1/2 Vel parameters).

### PR DESCRIPTION
**Pull request by MatthiasSeeber**
- [x] reworked envelope code to be more readable, generic and maintainable
- [x] closes #3158: introduced new envelope c loop functionality
- [x] closes #3251: fixed issues found on reviewing/reworking envelopes
- todo evaluate and optimize: at least some operations seem to be simd-compliant now
  - [x] envelope signal generation in audio-rate (not the rendering itself)

todo (after merge of [use-new-param-db](https://github.com/nonlinear-labs-dev/C15/tree/use-new-param-db)):
  - [x] add new parameters for envelope c (loop factor, decay 1/2 velocity) in configuration, synth
  - [x] playground, webui: introduce new parameters
  - [x] ui working
  - [x] thorough testing (loop factor, breakpnt/sustain, glitch suppression, flanger env)

### CODE REVIEW

**Comment by MatthiasSeeber** [comment]
Here is a first test via IDE: a triangular Envelope C Loop on SVF Cutoff and Resonance, Loop Factor is 175%. Flac and XML are included.

[LoopTest.zip](https://github.com/nonlinear-labs-dev/C15/files/9328960/LoopTest.zip)

**Review by MatthiasSeeber — COMMENTED** [review]
Unfortunately, the new envelope code seems to have a drastical performance cost.

| milestone-synthengine-update | issue-3158 |
| - | - |
| milestone-synthengine-update | issue-3158 |

**Comment by MatthiasSeeber** [comment]
Measured performance is now at 6.95586 x realtime. There still is a cost (despite some initial simd enhancements), which may be resolvable by further simd enhancements.

**Comment by MatthiasSeeber** [comment]
I now measure ~ 7.15 x realtime.

**Comment by schlenkibus** [comment]
decay und decay 2 velocity unter decay als slider
loop als modulierbares rundes control unter sustain

**Review by MatthiasSeeber — COMMENTED** [review]
status:
- [x] envelope soundcheck (incl. flanger env), modulateable loop
- [x] parameter infos
- [x] hwui/webui parameters
- [x] working presets

**Review by hhoegelo — APPROVED** [review]
I cannot say much to the changes in audio-engine, but the playground and nonmaps changes look good.

**Review by schlenkibus — APPROVED** [review]

**Pull request merged**
