### PR TITLE
BBB update: Playground service is stopped before the files are moved …

### PR DESCRIPTION
**Pull request by AntonSchmied**
…from BBB to ePC, to avoid overwriting of settings.xml and presets
This resolves Issue #1509

### CODE REVIEW

**Comment by AntonSchmied** [comment]
unless of course it makes more sense NOT to abort the update procedure completely, if we cannot stop the playground service.

**Comment by hhoegelo** [comment]
@AntonSchmied  I agree - the update process should NOT abort if stopping the playground fails.

**Comment by schlenkibus** [comment]
when will systemctl return an error? If it returns an error if the service is not running then i would prefer not aborting the update.

**Comment by AntonSchmied** [comment]
alright! let me just pull the latest from the master into the branch!

**Comment by AntonSchmied** [comment]
After a walk I have had a further thought:
in bbb_update.sh we're are currently checking the connection to the ePC just for the sake of eventually moving files, which might not even be there. This check has nothing to do with rsync-ing rootfs of the BBB. 
Suggestion: 
BBB to ePC connection + /persistent mount checks + moving files should only be carried out if the settings.xml is still present on the BBB under root? Is that a sufficient criterion?

**Comment by AntonSchmied** [comment]
@hhoegelo, Shlenki and I looked at the code and are happy with the procedure logic behind it. Could you check the code for sexiness please?

**Pull request merged**
