### PR TITLE
when downloading, patch the frame numbers in flac frames

### PR DESCRIPTION
**Pull request by hhoegelo**

### CODE REVIEW

**Review by MatthiasSeeber — CHANGES_REQUESTED** [review]
I'm afraid something went wrong. I cannot open a downloaded file on Linux 18.04 - regardless of which tool I use.

Screenshot from 2021-05-20 11-34-50

**Comment by MatthiasSeeber** [comment]
Here's a file freshly downloaded and a little longer than a few seconds. As described, no tool seems to be able to open/play it. Usually, the Linux File Info can identify flac codecs, with this file however, the File Info shows `n/a`.

I noticed that the VLC Media Player, despite not being able to properly open/identify or play the file, shows the expected file duration in the playlist view.

[C15-Recording-Thu-14-29-07-to-Thu-14-29-59.zip](https://github.com/nonlinear-labs-dev/C15/files/6515840/C15-Recording-Thu-14-29-07-to-Thu-14-29-59.zip)

**Comment by hhoegelo** [comment]
I found a bug writing utf8 numbers and fixed it.

**Review by MatthiasSeeber — APPROVED** [review]
For my system, this fixed the issue. Rhythmbox, Videos, VLC, Audacity run the file on Ubuntu 18.04. Linxu File Info also shows correct metadata. The duration was as expected.

**Comment by schlenkibus** [comment]
Same tests Matthias did, pass on Ubuntu 20 also.

**Review by schlenkibus — APPROVED** [review]

**Pull request merged**
