### PR TITLE
WebUI: Issue 3120: upload-firmware cancel-behaviour 

### LINKED ISSUE #3120: WebUI : cancelled "choose file" dialog for FW-upload is not reflected in calling window
When the "choose file" dialog is cancelled rather than an actual file selected, the dialog closes but the panel then wrongly shows "uploading" and you cannot enter the dialog again -- enabled, only after closing and re-invoking the "setup" panel.

### PR DESCRIPTION
**Pull request by schlenkibus**
moved setting label text to uploading.. only if we really are uploading, and remove last uploaded file after completion, so pressing cancel after succesfull upload will not pretend it has an file selected
closes #3120

### CODE REVIEW

**Review by KlausStrohhaecker — DISMISSED** [review]
Does not work here.
Cancelling still gives the "uploading..." message

**Comment by KlausStrohhaecker** [comment]
When I don't merge `main` into this branch (as we should do every morning) it suddenly works.
What's going wrong here?

**Review by hhoegelo — APPROVED** [review]

**Comment by schlenkibus** [comment]
I see no reason to break with our convention: not to merge to `main` directly. 
A merge to `milestone-synthengine-update` would be fine with me. 
Given that the feature is stable enough to be merged. I cant really tell what @KlausStrohhaecker test verdict was.

**Comment by schlenkibus** [comment]
@schlenkibus to answer my own question: seems to work fine still (tested from ide)

**Pull request merged**
