### PR TITLE
Update cosmetic repairs

### PR DESCRIPTION
**Pull request by AntonSchmied**
Sorry for the late PR.
This one includes minimal changes, which improve the update behavior!   
Chose the wrong branch for the PR first ...

### CODE REVIEW

**Comment by KlausStrohhaecker** [comment]
Hh, previous "install-update.sh" always freezes, new one never does, and run.sh, in a subsequent update, will return in case of success and thus system will continue after the update but will be inoperable (bridge stopped). Net effect is the same though, "restart" message will be displayed and C15 is stalled in either case and waiting for the the user to power-cycle.

Wouldn't the freeze() collide with the "reboot" option for OTA? That is, if there is any tiny error the OTA will probably leave the C15 bricked for further remote access?

**Comment by AntonSchmied** [comment]
let me have a think for a moment ...

**Comment by KlausStrohhaecker** [comment]
Most likely this are non-issues for the current release and things can be postponed.

**Comment by AntonSchmied** [comment]
I will have a think about what you mentioned! and then i'll get back to the PR

**Comment by AntonSchmied** [comment]
so, i still have to run a test or two just to be sure, but what do you think of this solution @KlausStrohhaecker?
concerning the ota <-> freeze: so far a manual restart of the C15 is the only solution, even if something goes south, yes .
I would suggest we think about this later on, since atm. it does not concern the users out there?

**Comment by AntonSchmied** [comment]
Tested: 
1905 -> 1.7: run.sh freezes on fail (ePC unpingable) instead of exiting to install-update.sh
1.5 -> 1.7: run.sh freezes on fail (ePC unpingable) instead of exiting to install-update.sh
1.7 -> 1.7: run.sh exits with 1 on fail (ePC unpingable) and install-update.sh freezes

**Comment by KlausStrohhaecker** [comment]
> so, i still have to run a test or two just to be sure, but what do you think of this solution @KlausStrohhaecker?
concerning the ota <-> freeze: so far a manual restart of the C15 is the only solution, even if something goes south, yes .
I would suggest we think about this later on, since atm. it does not concern the users out there?

We will have the occasional BBB network failure during update causing a stall/freeze but that is probably tolerable, we just need to tell the users that they must not worry and simply try again (power-cycle).

**Pull request merged**
