### PR TITLE
closes #2729

### LINKED ISSUE #2729: WebUI: Drag+Drop eines Presets auf ein Preset in einer anderen Bank ist wirkungslos. D+D auf den Header einer anderen Bank hängt das falsche Preset an.
- [x] Das Zielpreset sollte überschrieben werden. (Es wird ja flächig rote hervorgehoben.)

Beim Ziehen innerhalb der eigenen Bank funktioniert das Überschreiben. Insert durch D+D (rote Linie) funktioniert auch.

- [x] Bei Drop auf den Header einer anderen Bank (= Append) wird immer das gerade geladene Preset angehängt, auch wenn man ein anderes Preset dorthin zieht. Ausserdem wird das angehängte Preset fälschlicherweise als geladen markiert.

Beim Abschluss des D+D sollte das gedroppte Preset nie geladen werden. (So kann jemand Presets sortieren und jemand anderes kann ungestört weiterspielen.) Ausnahme: Verschieben des geladenen Presets durch D+D in der eigenen Bank.

### PR DESCRIPTION
**Pull request by schlenkibus**
- [x] renamed useCases to be more in-line with what the function actually does.
- [x] implemented `Preset::copyFrom` properly (we formerly used preset constructors)
- [x] add `appendPreset` useCase

### CODE REVIEW

**Review by MatthiasSeeber — CHANGES_REQUESTED** [review]
wie besprochen

**Comment by schlenkibus** [comment]
Lets not be too quick with merging this PR please. Lets talk about my fix and possible side-effects @MatthiasSeeber

**Review by MatthiasSeeber — CHANGES_REQUESTED** [review]
as discussed

**Review by MatthiasSeeber — APPROVED** [review]
Issue seems fixed, Undo problems and Crash with old preset overwrite seem fixed.
However, acceptance tests reveal one failing test case.

[issue-2720-acceptance-tests.txt](https://github.com/nonlinear-labs-dev/C15/files/6817034/issue-2720-acceptance-tests.txt)

(file should be named issue-2729-... - my bad)

**Review by MatthiasSeeber — APPROVED** [review]

**Review by hhoegelo — APPROVED** [review]

**Pull request merged**
