### PR TITLE
fixup short parameter labels

### LINKED ISSUE #1917: Kurzformen von vier Parameter-Labels aus Platz- und Konsistenz-Gründen ändern (s.u.)
- "Split Point" -> "Split Pnt" (Langform: "Split Point")
- "Key Prio" -> "Priority" (Langform: "Key Priority")
- "Part Vol" -> "Volume" (Langform: "Part Volume")
- "Part Tune" -> "Tune" (Langform: "Part Tune")

### PR DESCRIPTION
**Pull request by schlenkibus**
closes #1917

### CODE REVIEW

**Comment by schlenkibus** [comment]
> FYI:
> I prefer to update all files within the "generated" folder, even if they are not affected.
> This leads to the meta information of the generated files being up to date for all of them.

Which files did i forget? I did not copy ParameterFactory.java and mcview.js as they are currently not used

**Comment by MatthiasSeeber** [comment]
> > FYI:
> > I prefer to update all files within the "generated" folder, even if they are not affected.
> > This leads to the meta information of the generated files being up to date for all of them.
> 
> Which files did i forget? I did not copy ParameterFactory.java and mcview.js as they are currently not used

The Spreadsheet generates 3 header files (config, declarations, list). The "generated" folder however contains two other headers (descriptor, info), which I update manually when changing the Spreadsheet. I know, that's inconvenient. But, as mentioned, this is not a real issue. Maybe keep that in mind for the next time.

**Comment by schlenkibus** [comment]
> > > FYI:
> > > I prefer to update all files within the "generated" folder, even if they are not affected.
> > > This leads to the meta information of the generated files being up to date for all of them.
> > 
> > 
> > Which files did i forget? I did not copy ParameterFactory.java and mcview.js as they are currently not used
> 
> The Spreadsheet generates 3 header files (config, declarations, list). The "generated" folder however contains two other headers (descriptor, info), which I update manually when changing the Spreadsheet. I know, that's inconvenient. But, as mentioned, this is not a real issue. Maybe keep that in mind for the next time.

Okay, i was not aware of them, i usually just copy, paste and format the files generated by open office
I will try to think of the other files aswell, and adjust the date, if you prefer to keep that in sync. Although i believe that meta data like that should rather be pulled from git, as git will tell you when the content of the file changed. And updating the last modification date by hand, when nothing changes seems unnecessary.

**Comment by MatthiasSeeber** [comment]
> > > > FYI:
> > > > I prefer to update all files within the "generated" folder, even if they are not affected.
> > > > This leads to the meta information of the generated files being up to date for all of them.
> > > 
> > > 
> > > Which files did i forget? I did not copy ParameterFactory.java and mcview.js as they are currently not used
> > 
> > 
> > The Spreadsheet generates 3 header files (config, declarations, list). The "generated" folder however contains two other headers (descriptor, info), which I update manually when changing the Spreadsheet. I know, that's inconvenient. But, as mentioned, this is not a real issue. Maybe keep that in mind for the next time.
> 
> Okay, i was not aware of them, i usually just copy, paste and format the files generated by open office
> I will try to think of the other files aswell, and adjust the date, if you prefer to keep that in sync. Although i believe that meta data like that should rather be pulled from git, as git will tell you when the content of the file changed. And updating the last modification date by hand, when nothing changes seems unnecessary.

You're right, this system is rather inconvenient than useful. We may want to consider this when working on shared definitions in the future. So, nevermind the headers :)

**Pull request merged**
