### PR TITLE
fix #2170 - let everyone write to /persistent

### LINKED ISSUE #2170: sscl User apparently has no power over /persistent
When trying to scp files from BBB to ePC:/persistent, it results in failure due to the lack of permissions.
Example: 
`sshpass -p 'sscl' scp /internalstorage/foo sscl@192.168.10.10:/persistent`
`Warning: Permanently added '192.168.10.10' (ECDSA) to the list of known hosts.`
`scp: /persistent/foo: Permission denied`

`ls -lah /` on the ePC shows that only the SU has the appropriate rights for this:
`drwxr-xr-x   4 root root 4.0K Sep  4 11:59 persistent`

Can we allow sscl to have more power, please? Could make it a bit easier here and there.

### PR DESCRIPTION
**Pull request by hhoegelo**

### CODE REVIEW

**Comment by AntonSchmied** [comment]
I still can't seem to be able to copy a simlpe foo.txt from BBB:/tmp to ePC:/persistent
This was the initial idea behind the request.

`scp foo.txt sscl@192.168.10.10:/persistent
Warning: Permanently added '192.168.10.10' (ECDSA) to the list of known hosts.
sscl@192.168.10.10's password:
scp: /persistent/foo.txt: Permission denied`

**Comment by hhoegelo** [comment]
@AntonSchmied I (of course) tested it and for me it worked. Let's try it tomorrow on your setup to find the difference.

**Comment by AntonSchmied** [comment]
@hhoegelo Ready when you are 👍

**Comment by AntonSchmied** [comment]
We closed #2170, so we'll close this PR too.

**Pull request closed without merging**
