### PR TITLE
closes #2798

### LINKED ISSUE #2798: Voice-Allocation: Held note + setting Send Notes to off, leads to hung note in externals
we should send all notes/all sound off message whenever the note send settings have changed.

### PR DESCRIPTION
**Pull request by schlenkibus**
Stuck external notes should be fixed by sending CC 123 'All Notes Off' on both channels (if split is applicable) if the sending of MIDI notes is turned off

### CODE REVIEW

**Comment by schlenkibus** [comment]
@davidm2894 Preview Build is coming soon!

**Comment by schlenkibus** [comment]
@davidm2894 here we go: https://we.tl/t-4IjP33fa3a

**Comment by davidm2894** [comment]
no more stuck notes in split mode and whenever changing the routings. however, we still have stuck notes, when changing primary or split channel and holding down a key simultaneously.

**Comment by schlenkibus** [comment]
I didn't consider that. Thanks for pointing it out!

**Comment by schlenkibus** [comment]
new preview: https://we.tl/t-LZGNOrMF5J

**Review by hhoegelo — APPROVED** [review]

**Comment by davidm2894** [comment]
I still have stuck notes when changing send channel in both single and split mode. In split mode it doesn't matter if I change the channel wether of the primary or the split channel and holding down a key in the same channel, it will stuck either way.

Besides, I noticed that the "Global Local Enable" has lost its functionality.

**Pull request merged**
