### PR TITLE
Kstr pedal ui

### PR DESCRIPTION
**Pull request by hhoegelo**

### CODE REVIEW

**Comment by KlausStrohhaecker** [comment]
ToDo : Fix display width for the preset names in the preset selection screen, to use the maximum available space between the slider/percentage display and right display edge

**Comment by schlenkibus** [comment]
> ToDo : Fix display width for the preset names in the preset selection screen, to use the maximum available space between the slider/percentage display and right display edge

done

**Comment by hhoegelo** [comment]
@schlenkibus According to @KlausStrohhaecker there is some minor work still to do. Do you have all the information you need to finalize the issue?

**Comment by KlausStrohhaecker** [comment]
converted to draft as the actuel merge will be KSTR-PedalUI-->Master.
@schlenkibus : I can set up  some pseudo-code to assist, wrt to processing logic for the LPC initialization stuff.

**Comment by KlausStrohhaecker** [comment]
Something like this....
```
bool     lpcOnline     = false;
uint64_t heartBeat     = MAX_UINT64;
uint64_t lastHeartBeat = heartBeat;
uint32_t timeoutCntr   = 1;


void onLpcAnyMessageReceived(void)
{
  timeoutCntr = LPC_MSG_TIMEOUT; // > 100ms, maybe choose 500ms to avoid spurious false "offline" detection
  lpcOnline   = true;
}


void OnLpcHeartBeatReceived(uint64_t hb)
{
  lastHeartBeat = heartBeat;
  heartBeat     = hb;
}


void SomeMainLoopCalledAtFixedTimeSlice(void) // something like 10ms, with only moderate jitter
{
  if (timeoutCntr)
  {
    if (!--timeoutCntr)  // timeout indicates a very likely offline state
      lpcOnline = false;
  }

  if (heartBeat < lastHeartBeat)
    lpcOnline = false;  // heartbeat fault forces offline state
  

  if (lpcOnline != lastLpcOnline)
  {
    lastLpcOnline = lpcOnline;
    if (lpcOnline)  // LPC went online now
    {
      SendGlobalLpcInitData();
      SendPresetSpecificLpcData();
      SendEditBufferToAudioEngine();
      ...
    }
  }
  // lpcOnline should be used as a global flag, in LPCpoxy etc, never send anything to LPC when it is offline
}


void OnEditBufferChange(void)
{
  SendPresetSpecificLpcData();
  SendEditBufferToAudioEngine();
  ...
}


void SendGlobalLpcInitData(void)
{
  // unconditional sends !
  sendSetting(LPC_SETTING_ID_BASE_UNIT_UI_MODE);
  sendSetting(LPC_SETTING_ID_EDIT_MODE_RIBBON_BEHAVIOUR);
  sendSetting(LPC_SETTING_ID_RIBBON_REL_FACTOR);
  sendSetting((LPC_SETTING_ID_VELOCITY_CURVE);
  sendSetting(LPC_SETTING_ID_AFTERTOUCH_CURVE);
  sendSetting(LPC_SETTING_ID_BENDER_CURVE);
  
  SendPedalSetup(PEDAL_1);  // use data from settings.xml, but settings might have been ...
  SendPedalSetup(PEDAL_2);  // ... updated meanwhile in the pedal editor, only then reset flag shall be set.
  SendPedalSetup(PEDAL_3);  // Note: realtime changes in PedalEditor while LPC is online ...
  SendPedalSetup(PEDAL_4);  // ... must always call PedalSetup *with* Reset, then clear the "update" flag, see below
  
  SendRibbonCalibration();  // use direct LPC message from /persistent/calibation/calibration.bin, if missing, ignore (no error/warning)
}


void SendPedalSetup(id)
{
  bool reset = CheckAndClear_PedalHasBeenUpdatedInPedalEditor(id);
  PedalSetup(id, reset);
}


SendPresetSpecificLpcData()
{
  // unconditional sends !
  sendSetting(LPC_SETTING_ID_PLAY_MODE_UPPER_RIBBON_BEHAVIOUR);  // note side effect when BASE_UNIT_UI_MODE is EDIT_CONTROL
  sendSetting(LPC_SETTING_ID_PLAY_MODE_LOWER_RIBBON_BEHAVIOUR);  // note side effect when BASE_UNIT_UI_MODE is EDIT_CONTROL
  // note the sequencing, PLAY_MODE_BEHAVIORs must be set first
  sendSetting(LPC_SETTING_ID_UPPER_RIBBON_VALUE);
  sendSetting(LPC_SETTING_ID_LOWER_RIBBON_VALUE);
}
```

**Pull request closed without merging**
