### PR TITLE
Issue 2023

### LINKED ISSUE #2023: MacroControl Fehlerhafter Ruecksprung bei Bereichsüberschreitung
Beta 20-25 RC03
branch       RELEASE-2020-06
commits     4524
head          2fe0d1733
rt version   2.06

Wenn ein Macrocontrol auf 50% in Verbindung mit Pitchbender steht, führen Zuordnungen von HW_Sources mit höheren Grenzen zu Verschiebungen des Returnwertes.

**Beispiel 1 :** 

Init Preset mit Pitch auf +/-2 auf MC-C geroutet 
- MC-C HW Pos steht auf **50**%
- Hw sources 
         Pitchbender mit **50**% amount
         Aftertouch mit **100**% amount

Bei Benutzung :

         1. Taste anschlagen und halten, (oder release auf inf)
         2. Pitchbender links -> pitch = -2 -> OK
         3. PB loslassen -> pitch =  0 -> OK
         4. PB nach rechts -> pitch = +2 -> OK
         5. PB loslassen -> 0 -> OK
         6. Aftertouch komlpett drücken -> pitch = +2 ->OK
         7. AT loslassen -> pitch = -2 -> fail , sollte auf 0 gehen
         8. AT drücken -> pitch = +2 -> ok 

Beispiel 2 : 

Init Preset mit Pitch auf +/-2 auf MC-C geroutet 
- MC-C HW Pos steht auf **50**%
- Hw sources 
         Pitchbender mit **100**% amount

Auch hier bekommt man keine saubere Möglichkeit mehr den Pitchbender einzusetzen. 

Ich denke was passiert ist folgendes:
Bei 100 % Auslenkung der HW source bei nur 50% 'Platz' in der Modulation  wird zwar das Modulationsergebnis geclippt, was richjtig ist, jedoch wird beim Loslassen bzw Rückstellen der HW Source Gesamte Wert wieder abgezogen und liefert somit einen falschen Returnwert.

Zum Ausprobieren ein Preset für Beipiel 1 im Anhang
[test modulations.xml.zip](https://github.com/nonlinear-labs-dev/C15/files/4840265/test.modulations.xml.zip)

Ich denke das ist ein Effekt der bei allen Return-To-Center-HW-Sources auftreten kann.

p.s. : ;Man kann die im Beispiel gewählten Einstellungen evtl. als Fehlbedienung interpretieren, aber das Verhalten zur 1.5/ Reaktor unterscheidet sich. Einge Presets sind selbst nach Adaption der Einstellungen von mir  nicht mehr gleichwertig benutzbar- oder ich bin zu blöd ;)

### PR DESCRIPTION
**Pull request by MatthiasSeeber**
fixes #2023
(Macro Controls should now behave properly when clipping by a returning HW Source occurs.)

### CODE REVIEW

**Comment by majjam** [comment]
Tested the branch with my 1st given example. No issues here.

But i have another example where I'm not sure whether its the same or similar effect in the opposite modulation direction.

Now i assigned pedal4 instead of AT to MC-C together with Pitchbender 
Pedal 4 is Roland DP 10 / damper Pedal with spring.
After using the pedal, the pitch mod goes down to 0,
the Pitchbender only adds the positive side of modulation afterwards.

To be honest i do not have any logic solution for that.
My goal is to be able to set the base of the modulation by pitch bender and ADD the pedal 4 towards it, maybe there is no clear way to do that.
Anyway to see what i mean attached the same bank with a second preset.


[test modulations (2).xml.zip](https://github.com/nonlinear-labs-dev/C15/files/4842032/test.modulations.2.xml.zip)

**Comment by MatthiasSeeber** [comment]
I strongly suspect it is the "Non-Return" Behavior of the Pedal. When a Pedal or Ribbon is in "Non-Return", they simply overwrite the Macro instead of adding to it - as indicated by arrows instead of sliders in the Mod Matrix. The Bender on the other hand always returns and hence always tries to add its movement (weighted by the corresponding Amount Slider) - so the different Source Behaviors collide here.

Try a "Return to Zero/Center" behavior for your pedal instead and set the HW Amount via the slider, now everything should work as expected.

Screenshot from 2020-06-28 12-18-35

**Comment by majjam** [comment]
Definitely my fault ! [The user is always the fault]  Putting the pedal to a return behaviour is what thought i did, but didn't do. Thanks or helping me out here.

So from my side this topic is clear.

**Comment by MatthiasSeeber** [comment]
This PR was merged git-only (due to server-down), see https://github.com/nonlinear-labs-dev/C15/commit/a10dc852752a5e062b76b9fb337cabbb1a5348da
(both master and RELEASE-2020-06 are up-to-date)
Therefore, this PR will be manually closed.

**Pull request closed without merging**
