### PR TITLE
[S.E.Upd.22] parameter enhancements

### LINKED ISSUE #1563: Parameter Revision - Modulateables
We intend to re-classify many parameters as modulateables. @nonlinear-labs when the concept is established and all re-classifications are known, the ParameterList document can be placed within this issue.

### LINKED ISSUE #2908: MC-Modulationsmöglichkeit für fast alle Parameter
In der folgenden Parameter Tabelle sind alle neu hinzugekommenen Modulationsziele grün markiert.

[ParameterList_1.7B neue Targets ssc.ods](https://github.com/nonlinear-labs-dev/C15/files/7507854/ParameterList_1.7B.neue.Targets.ssc.ods)

Nicht moduliert werden sollen:
- Velocity Amounts
- Key Tracking und Key Panning Amounts
- Unison Voices
- Mono Modes

Audio-Störungen können auftreten bei schlecht oder nicht gesmoothten Parametern wie Reverb - Pre Delay.
Bei Verbesserungen im Smoothing müssen wir die Auswirkungen auf die CPU-Last beobachten.

### LINKED ISSUE #2919: [Local: Off] Provide Info Texts for secondary HW Source Parameters
### Attention
We have to be careful about the order of changing the ParameterList.ods, so #2874 and #2916 need to be merged first. *(the file is binary and parallel, branch-based changes cannot be merged by gh)*

### Goal
When in MIDI Mode Local OFF, the secondary HW Parameters should be visible. As they are displayed as ordinary Parameters, we require Info Texts for them.

### Proposition
~~~
When the MIDI Local Setting is disabled, this control is the
parameter representation of the "Pedal 1" Hardware Source.
It reflects changes that will be sent when the MIDI Channels
Settings allow for MIDI to be sent without affecting the Synth.

This parameter will be visible next to the internal representation
of "Pedal 1" (which reflects changes from the User Interface or
MIDI Input, only affecting the Synth).
~~~

@nonlinear-labs, @davidm2894 please discuss further in the comments.

### LINKED ISSUE #2920: Erweiterte Bereiche für einige Key Trackings, Key Panning, einige Velocities, Unison Detune
- [x] Output Mixer - Key Pan: -100.0 ... 100.0 % (auch in #2756)
- [x] Oscillator A - Pitch - Key Trk: 0.00 ... 200.00 %
- [x] Oscillator B - Pitch - Key Trk: 0.00 ... 200.00 %
- [x] Comb Filter - Pitch - Key Trk: 0.00 ... 200.00 %
- [x] Comb Filter - AP Tune - Key Trk: 0.0 ... 200.0 %
- [x] Comb Filter - Hi Cut - Key Trk: 0.0 ... 200.0 %
- [x] SV Filter - Cutoff - Key Trk: 0.0 ... 200.0 %
- [x] Unison - Detune: 0.00 ... 24.00 st
- [x] Envelope A - Attack Velocity: -100.0 ... 100.0 %
- [x] Envelope B - Attack Velocity: -100.0 ... 100.0 %
- [x] Envelope C - Attack Velocity: -100.0 ... 100.0 %
- [x] Envelope A - Time Key Trk: -100.0 ... 100.0 % ~~(intuitiver, wenn man die bisherigen 0...100% auf 0...-100% mappt?)~~ 
- [x] Envelope B - Time Key Trk: -100.0 ... 100.0 %
- [x] Envelope C - Time Key Trk: -100.0 ... 100.0 %

Envelope X Attack - Velocity -> DB_t instead of %

### LINKED ISSUE #2921: Shaper A/B - FB - Env C: Bereich auf -100 % ...100 % erweitern. Negativer Teil dient zum Bypassen des Gates
100 % : Envelope C voll wirksam
0% : Gate voll wirksam
-100 %: Gate unwirksam, Signalweg permanent offen (Multiplikation mit 1)

Im positiven Bereich crossfaden wir - wie bisher - zwischen dem Gate-Signal und dem Envelope-Signal. Im negativen Bereich zwischen dem Gate-Signal und der konstanten 1.

Das Gate hilft, ein Dauer-Feedback (Durchpfeifen) beim Loslassen der Taste zu vermeiden. Es ist in Physical-Modeling-Strukturen aber oft störend, weil die Töne nach dem Loslassen der Taste nicht natürlich abklingen. Mit dem Envelope C mit langer Release-Zeit kann man das zwar umgehen, damit ist aber der Envelope für nicht anderes mehr verfügbar. Ausserdem ist er dafür "überqualifiziert".
Der neue negative Range eignet sich auch gut für die Anwendung eines Sustain/Damper-Pedals.

Der Parameter könnte vielleicht umbenannt werden in "FB - Gate/Env C".

### PR DESCRIPTION
**Pull request by MatthiasSeeber**
### Attention

This PR deals with new features of the [Synth Engine Update 2021](https://github.com/nonlinear-labs-dev/C15/milestone/14) Milestone. It should remain a **Draft** until `unstable` is considered ready for new features. This depends on the progress of the A1/A2 ("Hotfix") Milestones.

As the unmergable Parameter List is affected and several other tickets require minor changes, this PR combines several tasks - at least for the List and Synth Engine. Playground tasks are listed below as well.

### Tasks

1. closes #2908, closes #1563
- [x] update ParameterList.ods and parameter-db header files - AudioEngine should be ready *(preset and parameter changes are expected to be broken now)*
- [x] implement parameter type changes in Playground and WebUI *(some small Sliders like `Pitch Env C` now require MC indication, changed parameters will have to migrate in preset messages to `modulateables` and param changed msg `ModulateableParameterChangedMessage`)*
2. closes #2919
- [x] update ParameterList.ods and parameter-db header files
3. closes #2920
- [x] update ParameterList.ods and parameter-db header files, verify/extend parameter info
- [x] verify/repair/extend audio engine (verified)
- [x] implement parameter range changes in Playground and WebUI
4. closes #2921
- [x] update ParameterList.ods and parameter-db header files, verify/extend parameter info
- [x] verify/repair/extend audio engine (extended)
- [x] implement parameter range changes in Playground and WebUI
5. **cleanup, tests**
- [x] version control: introduce new Bank Version to reflect the parameter configuration changes
- [x] fix merge conflicts
- [ ] when preset and parameter changes are working again, we should be ready for testing for audible smoothing artifacts (1.) or other unexpected

### CODE REVIEW

**Comment by KlausStrohhaecker** [comment]
Proposing cosmetic fix in /projects/shared/parameter-db/CMakeLists.txt:
It's called "spreadsheet", not "spritesheet" ;-)

**Review by MatthiasSeeber — COMMENTED** [review]
Synth Engine can be considered ready for Testing.
UI / Playgorund can implement the new features now:
- #2908: changing Parameter Types, affects Boled/WebUI parameter display, ParameterChanged and Preset Message composition
- #2920, #2921: Parameter Polarity and/or Range changes affect Preset Conversion
- all changes require new Bank Version

**Review by MatthiasSeeber — COMMENTED** [review]
## Synth + UI
For most of the functionality (at least all the rudimentary stuff) I already can give approval:
- [x] Modulation mechanism
- [x] Store/Recall
- [x] up-to-date Parameter Infos

There however are some details left:
- WebUI: change mechanism seems totally broken?
- (probably separate issue) Boled on Scale Params: Soft Button conflict
- (probably separate issue) Smoothing Artifacts: Flanger (Phase, Env), Reverb (PreDly) already known
- [x] Mod Amount Unit for Env params (when main Param is in Semitones): Amount Unit should be ST, not %
- [ ] new range conversion:
  - Init on Env Time KT produces 2.5% instead of 5%? (recall seems to be okay though)
  - Init on Comb LP KT produces 200% instead of 100%? (recall seems to be okay though)
- [x] parameter-db (see [#3106](https://github.com/nonlinear-labs-dev/C15/pull/3106)): Comb AP & LP KeyTrk params have still 1.0 scaling factor (instead of 2.0), initial DV wrongfully set to 200.0 (this causes the sound to be wrong for those parameters)

## Code
I just checked functionality. This PR unfortunately doesn't seem to recognize that most of the 200+ commits from A2+A3 already are in this branch and the target branch. Maybe, we transfer this to a new pull request? (This would drastically reduce the number of commits shown here)

**Comment by schlenkibus** [comment]
This PR has been reopened as: https://github.com/nonlinear-labs-dev/C15/pull/3118

**Pull request closed without merging**
